- envs/jruby/README.md
- envs/jruby/shell.nix
JRuby unlike **ruby** in _nixpkgs_ does not apply a patch to change the default gem installation directory.
As a result whomever uses it must specify _GEM_HOME_.
I consider that _gotcha_ enough to warrant having it in this repo as non-trivial.
> Add environment for JRuby

- envs/arduino/shell.nix
Without ncurses, this shell will fail with "bash: tput: command not found"
> arduino: add ncurses dependency to targetPkgs

- envs/openwrt/shell.nix
Fixes build error in `master` together with #34
> openwrt: replace removed alias utillinux -> util-linux

- envs/yocto/shell.nix
Fixes build error in `master` together with #33
> yocto: replace removed alias lzma -> xz

- envs/xilinx-vitis/shell.nix
These where missing to use a vitis 2023.x environment. Fixes #49.
> add python and libxcrypt-legacy to xilinx-vitis environment

- default.nix
- envs/openwrt/shell.nix
This change allows to use the openwrt environment as a standalone fhs environment within a CI.
For example:
```
name: Build OpenWrt images
on:
repository_dispatch:
workflow_dispatch:
push:
tags:
- "v*"
jobs:
build-openwrt-images:
runs-on: ubuntu-22.04
defaults:
run:
shell: nix develop .#openwrt-ci --command bash {0}
steps:
- name: Checkout
uses: actions/checkout@v3
- uses: cachix/install-nix-action@v22
with:
nix_path: nixpkgs=channel:nixos-unstable
- name: prepare source
run: |
echo "hello from within the nix devShell"
```
> add openwrt-ci (fhs without .env)

- envs/yocto/shell.nix
`devtool add` requires `setuptools`.
> yocto: add missing setuptools, used by devtool.

- README.md
Currently, the readme only provides an example on how to override attributes for non-buildFHSUserEnv-based environments. I needed to add a few additional packages to my yocto environment and struggled to find any information on how override buildFHSUserEnv-derivations in general until I came up with the solution in this PR.
I don't know whether this is the intended to use the extraPkgs attribute, so feel free to correct me if there is a better way to use it and I'll happily update this PR.
> update README to include information on how to modify buildFHSUserEnv-based environments

- envs/home-assistant/shell.nix
> Use python 3.12 for Home Assistant

- envs/yocto/shell.nix
Recent _scarthgap_ `meta-xilinx-core` depends on  `pyaml`. 
```
[alain@desktop:~/projects/stt/its2-yocto/build]$ devtool status
NOTE: Starting bitbake server...
Traceback (most recent call last):
File "/home/alain/projects/stt/its2-yocto/meta/poky/scripts/devtool", line 350, in <module>
ret = main()
File "/home/alain/projects/stt/its2-yocto/meta/poky/scripts/devtool", line 305, in main
scriptutils.load_plugins(logger, plugins, pluginpath)
File "/home/alain/projects/stt/its2-yocto/meta/poky/scripts/lib/scriptutils.py", line 96, in load_plugins
plugin = load_plugin(name)
File "/home/alain/projects/stt/its2-yocto/meta/poky/scripts/lib/scriptutils.py", line 85, in load_plugin
spec.loader.exec_module(mod)
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen …
```
> yocto: add pyaml library.

- envs/infinisim/README.md
- envs/infinisim/shell.nix
The optional feature to process images for the emulated storage uses libpng12.
> envs/infinisim: add libpng12

- envs/infinitime/README.md
- envs/infinitime/shell.nix
buildFHSUserEnv has some drawbacks so it is preferrable if possible to use a pkgs.mkShell instead.
Also add two dependencies required for some build options.
- adafruit-nrfutil
- python3.packages.pillow
> envs/infinitime: use mkshell instead of buildFHS

- README.md
- default.nix
- envs/buildroot/README.md
- envs/buildroot/shell.nix
Add env config which allows to build a buildroot system.
> envs: add buildroot shell.nix

- README.md
- default.nix
- envs/git/README.md
- envs/git/shell.nix
This `shell.nix` file provides an environment that allows building and testing git with `make`. The tools/libraries included were determined by reviewing git's `INSTALL` document [1] followed by some trial and error.
Exporting `PERL_PATH` as an environment variable allows both the build and test processes to work despite `perl` not being present at `/usr/bin/perl` on a standard NixOS install.
Tested on both `x86_64-linux` and `aarch64-darwin`.
[1]: https://github.com/git/git/blob/2e7b89e038c0c888acf61f1b4ee5a43d4dd5e94c/INSTALL#L110
> git: add shell environment for git.git

- envs/infinitime/shell.nix
- envs/yocto/shell.nix
This has been default in the default poky distribution for a while, but according to https://manpages.debian.org/testing/lz4/lz4c.1.en.html, it's just an alias to `lz4`
> envs/yocto: add missing lz4c alias for scarthgap

- envs/yocto/shell.nix
I did bump into this issue w/ NixOS 24.11.
> yocto: fix for missing libcrypt.so.1.

- envs/yocto/shell.nix
Replace buildFHSUserEnv and buildFHSUserEnvBubblewrap, with buildFHSEnv and buildFHSEnvBubblewrap, to fix deprecation warning.
Tested against master and nixos-unstable branches of nixpkgs. The stable branch does not seem to work anyway with this Yocto environment
> yocto: Fix deprecation warnings

- envs/openwrt/shell.nix
These should absoluetly not point to the gcc wrapper, they are thin wrappers around the binutils tools that are necessary to make LTO work.
This fix link failures in apk, where Meson would (I assume) see a broken x86_64-unknown-linux-gnu-gcc-ar (or a missing gcc-ar), and fall back to the unwrapped ar.
> openwrt: fix gcc-{ar,nm,ranlib} symlinks

- envs/yocto/shell.nix
This is required if the upstream sstate server should be used, as shown in
https://docs.yoctoproject.org/singleindex.html#building-your-image
> yocto: add python websockets package

- README.md
- envs/arduino/README.md
- envs/arduino/shell.nix
- envs/buildroot/README.md
- envs/buildroot/shell.nix
- envs/openwrt/shell.nix
- envs/spec-benchmark/shell.nix
- envs/xilinx-vitis/shell.nix
This is to fix the warning:
```
evaluation warning: 'buildFHSUserEnv' has been renamed to 'buildFHSEnv' and will be removed in 25.11
```
Just did a sed find and replace with command `sed -i "s/buildFHSUserEnv/buildFHSEnv/g" ./**/*.md ./**/*.nix`
`nix flake check` reports no issues, and every shell can be be built and entered correctly.
Tested the building and entering using 
```nu
for shell in (ls ./envs/* -s | where type == 'dir' | get name) 
{
print $'Building env for ($shell)'; nix-shell -A ($shell);
}
```
Have not re verified the functionality of the shells.
> fix: rename buildFHSUserEnv to buildFHSEnv, fixing warnings

- envs/home-assistant/shell.nix
This was causing issues because it was using an old setuptools version.
Apparently setuptools does not need to be pulled from nixpkgs now for
HA.
> Remove setuptools from Home Assistant

- envs/ladybird/README.md
Copy and paste error from the old ladybird docs oopsie
> ladybird: fix typo in build instructions
